M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu22.04.1} date Tue 18 Apr 2023 04:50:03 PM EDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-18T16:50:03-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
%
G90
G05
T1
X208.97Y-71.53
X208.97Y-99.47
T0
M30
