Revision 2
; Created by makebits version 4.8.12 at 94/05/03 16:08:41.
;    Offset   Column (Frame) Row (Frame Offset) Description
         4                1               67 Dummy
         7                1               64 Latch P29 Q 
        12                1               59 Dummy
        15                1               56 Latch P30 Q 
        24                1               47 Latch P31 Q 
        29                1               42 Dummy
        31                1               40 Dummy
        32                1               39 Dummy
        33                1               38 Dummy
        37                1               34 Dummy
        40                1               31 Latch P34 Q 
        49                1               22 Latch P35 Q 
        54                1               17 Dummy
        57                1               14 Latch P36 Q 
        62                1                9 Dummy
        63                1                8 Dummy
        64                1                7 Dummy
        65                1                6 Dummy
       101                2               41 Dummy
       102                2               40 Dummy
       103                2               39 Dummy
       104                2               38 Dummy
       134                2                8 Dummy
       135                2                7 Dummy
       136                2                6 Dummy
       146                3               67 Dummy
       172                3               41 Dummy
       173                3               40 Dummy
       175                3               38 Dummy
       205                3                8 Dummy
       206                3                7 Dummy
       242                4               42 Dummy
       244                4               40 Dummy
       275                4                9 Dummy
       277                4                7 Dummy
       288                5               67 Dummy
       290                5               65 Dummy
       359                6               67 Dummy
       361                6               65 Dummy
       430                7               67 Dummy
       431                7               66 Dummy
       457                7               40 Dummy
       490                7                7 Dummy
       501                8               67 Dummy
       502                8               66 Dummy
       530                8               38 Dummy
       572                9               67 Dummy
       574                9               65 Dummy
       582                9               57 Latch U28 Q 
       591                9               48 Latch U26 Q 
       599                9               40 Latch P32 Q 
       601                9               38 Dummy
       607                9               32 Latch U23 Q 
       616                9               23 Latch U21 Q 
       624                9               15 Latch U19 Q 
       632                9                7 Latch P37 Q 
       858               13               65 Latch HH Q 
       866               13               57 Latch GH Q 
       875               13               48 Latch FH Q 
       883               13               40 Latch EH Q 
       891               13               32 Latch DH Q 
       900               13               23 Latch CH Q 
       908               13               15 Latch BH Q 
       916               13                7 Latch AH Q 
       924               14               70 Latch P25 Q 
       992               14                2 Latch P40 Q 
      1207               18               71 Latch P26 Q 
      1277               18                1 Latch P39 Q 
      1347               19                2 Dummy
      2136               31               65 Latch HG Q 
      2144               31               57 Latch GG Q 
      2153               31               48 Latch FG Q 
      2161               31               40 Latch EG Q 
      2169               31               32 Latch DG Q 
      2178               31               23 Latch CG Q 
      2186               31               15 Latch BG Q 
      2194               31                7 Latch AG Q 
      2202               32               70 Latch U33 Q 
      2270               32                2 Latch P42 Q 
      2485               36               71 Latch P24 Q 
      2555               36                1 Latch P41 Q 
      2625               37                2 Dummy
      3556               51               65 Latch HF Q 
      3564               51               57 Latch GF Q 
      3573               51               48 Latch FF Q 
      3581               51               40 Latch EF Q 
      3589               51               32 Latch DF Q 
      3598               51               23 Latch CF Q 
      3606               51               15 Latch BF Q 
      3614               51                7 Latch AF Q 
      3622               52               70 Latch U35 Q 
      3690               52                2 Latch P43 Q 
      3905               56               71 Latch U34 Q 
      3975               56                1 Latch U12 Q 
      4045               57                2 Dummy
      4834               69               65 Latch HE Q 
      4842               69               57 Latch GE Q 
      4851               69               48 Latch FE Q 
      4859               69               40 Latch EE Q 
      4867               69               32 Latch DE Q 
      4876               69               23 Latch CE Q 
      4884               69               15 Latch BE Q 
      4892               69                7 Latch AE Q 
      4900               70               70 Latch U37 Q 
      4968               70                2 Latch P44 Q 
      5183               74               71 Latch U36 Q 
      5253               74                1 Latch U10 Q 
      5323               75                2 Dummy
      6112               87               65 Latch HD Q 
      6120               87               57 Latch GD Q 
      6129               87               48 Latch FD Q 
      6137               87               40 Latch ED Q 
      6145               87               32 Latch DD Q 
      6154               87               23 Latch CD Q 
      6162               87               15 Latch BD Q 
      6170               87                7 Latch AD Q 
      6178               88               70 Latch U39 Q 
      6246               88                2 Latch P2 Q 
      6461               92               71 Latch P22 Q 
      6531               92                1 Latch U8 Q 
      6601               93                2 Dummy
      7532              107               65 Latch HC Q 
      7540              107               57 Latch GC Q 
      7549              107               48 Latch FC Q 
      7557              107               40 Latch EC Q 
      7565              107               32 Latch DC Q 
      7574              107               23 Latch CC Q 
      7582              107               15 Latch BC Q 
      7590              107                7 Latch AC Q 
      7598              108               70 Latch U41 Q 
      7666              108                2 Latch P3 Q 
      7881              112               71 Latch P21 Q 
      7951              112                1 Latch U6 Q 
      8021              113                2 Dummy
      8810              125               65 Latch HB Q 
      8818              125               57 Latch GB Q 
      8827              125               48 Latch FB Q 
      8835              125               40 Latch EB Q 
      8843              125               32 Latch DB Q 
      8852              125               23 Latch CB Q 
      8860              125               15 Latch BB Q 
      8868              125                7 Latch AB Q 
      8876              126               70 Latch U43 Q 
      8944              126                2 Latch P5 Q 
      9159              130               71 Latch P20 Q 
      9229              130                1 Latch P4 Q 
      9299              131                2 Dummy
     10088              143               65 Latch HA Q 
     10096              143               57 Latch GA Q 
     10105              143               48 Latch FA Q 
     10113              143               40 Latch EA Q 
     10121              143               32 Latch DA Q 
     10130              143               23 Latch CA Q 
     10138              143               15 Latch BA Q 
     10146              143                7 Latch AA Q 
     10154              144               70 Latch P18 Q 
     10222              144                2 Latch P7 Q 
     10227              145               68 Dummy
     10302              146               64 Dummy
     10310              146               56 Dummy
     10319              146               47 Dummy
     10327              146               39 Dummy
     10329              146               37 Dummy
     10335              146               31 Dummy
     10344              146               22 Dummy
     10352              146               14 Dummy
     10360              146                6 Dummy
     10373              147               64 Dummy
     10400              147               37 Dummy
     10437              148               71 Latch P19 Q 
     10469              148               39 Dummy
     10502              148                6 Dummy
     10507              148                1 Latch P6 Q 
     10516              149               63 Dummy
     10577              149                2 Dummy
     10586              150               64 Dummy
     10644              150                6 Dummy
     10670              151               51 Dummy
     10695              151               26 Dummy
     10787              152                5 Dummy
     11037              156               39 Dummy
     11070              156                6 Dummy
     11108              157               39 Dummy
     11110              157               37 Dummy
     11112              157               35 Dummy
     11141              157                6 Dummy
     11145              157                2 Dummy
     11151              158               67 Dummy
     11152              158               66 Dummy
     11153              158               65 Dummy
     11156              158               62 Latch U46 Q 
     11164              158               54 Latch U48 Q 
     11173              158               45 Latch P13 Q 
     11179              158               39 Dummy
     11181              158               37 Dummy
     11183              158               35 Dummy
     11189              158               29 Latch U53 Q 
     11198              158               20 Latch U55 Q 
     11206              158               12 Latch U57 Q 
     11222              159               67 Dummy
     11223              159               66 Dummy
     11224              159               65 Dummy
     11250              159               39 Dummy
     11254              159               35 Dummy
     11293              160               67 Dummy
     11294              160               66 Dummy
     11295              160               65 Dummy
     11301              160               59 Latch P15 Q 
     11310              160               50 Latch P14 Q 
     11318              160               42 Latch U51 Q 
     11321              160               39 Dummy
     11325              160               35 Dummy
     11326              160               34 Latch U52 Q 
     11335              160               25 Latch P11 Q 
     11343              160               17 Latch P10 Q 
     11351              160                9 Latch P9 Q 
