Revision 2
; Created by makebits version 4.8.12 at 94/05/03 16:05:43.
;    Offset   Column (Frame) Row (Frame Offset) Description
         4                1               83 Dummy
         7                1               80 Latch P29 Q 
        12                1               75 Dummy
        15                1               72 Latch P30 Q 
        20                1               67 Dummy
        23                1               64 Latch U33 Q 
        32                1               55 Latch P31 Q 
        37                1               50 Dummy
        39                1               48 Dummy
        40                1               47 Dummy
        41                1               46 Dummy
        45                1               42 Dummy
        48                1               39 Latch P34 Q 
        57                1               30 Latch U26 Q 
        62                1               25 Dummy
        65                1               22 Latch P35 Q 
        70                1               17 Dummy
        73                1               14 Latch P36 Q 
        78                1                9 Dummy
        79                1                8 Dummy
        80                1                7 Dummy
        81                1                6 Dummy
       125                2               49 Dummy
       126                2               48 Dummy
       127                2               47 Dummy
       128                2               46 Dummy
       166                2                8 Dummy
       167                2                7 Dummy
       168                2                6 Dummy
       178                3               83 Dummy
       212                3               49 Dummy
       213                3               48 Dummy
       215                3               46 Dummy
       253                3                8 Dummy
       254                3                7 Dummy
       298                4               50 Dummy
       300                4               48 Dummy
       339                4                9 Dummy
       341                4                7 Dummy
       352                5               83 Dummy
       354                5               81 Dummy
       439                6               83 Dummy
       441                6               81 Dummy
       526                7               83 Dummy
       527                7               82 Dummy
       561                7               48 Dummy
       602                7                7 Dummy
       613                8               83 Dummy
       614                8               82 Dummy
       650                8               46 Dummy
       700                9               83 Dummy
       702                9               81 Dummy
       710                9               73 Latch U36 Q 
       718                9               65 Latch U34 Q 
       727                9               56 Latch U32 Q 
       735                9               48 Latch P32 Q 
       737                9               46 Dummy
       743                9               40 Latch U29 Q 
       752                9               31 Latch U27 Q 
       760                9               23 Latch U25 Q 
       768                9               15 Latch U23 Q 
       776                9                7 Latch P37 Q 
      1050               13               81 Latch JJ Q 
      1058               13               73 Latch IJ Q 
      1066               13               65 Latch HJ Q 
      1075               13               56 Latch GJ Q 
      1083               13               48 Latch FJ Q 
      1091               13               40 Latch EJ Q 
      1100               13               31 Latch DJ Q 
      1108               13               23 Latch CJ Q 
      1116               13               15 Latch BJ Q 
      1124               13                7 Latch AJ Q 
      1132               14               86 Latch P25 Q 
      1216               14                2 Latch P40 Q 
      1479               18               87 Latch P26 Q 
      1565               18                1 Latch P39 Q 
      1651               19                2 Dummy
      2616               31               81 Latch JI Q 
      2624               31               73 Latch II Q 
      2632               31               65 Latch HI Q 
      2641               31               56 Latch GI Q 
      2649               31               48 Latch FI Q 
      2657               31               40 Latch EI Q 
      2666               31               31 Latch DI Q 
      2674               31               23 Latch CI Q 
      2682               31               15 Latch BI Q 
      2690               31                7 Latch AI Q 
      2698               32               86 Latch U41 Q 
      2782               32                2 Latch P42 Q 
      3045               36               87 Latch P24 Q 
      3131               36                1 Latch P41 Q 
      3217               37                2 Dummy
      4182               49               81 Latch JH Q 
      4190               49               73 Latch IH Q 
      4198               49               65 Latch HH Q 
      4207               49               56 Latch GH Q 
      4215               49               48 Latch FH Q 
      4223               49               40 Latch EH Q 
      4232               49               31 Latch DH Q 
      4240               49               23 Latch CH Q 
      4248               49               15 Latch BH Q 
      4256               49                7 Latch AH Q 
      4264               50               86 Latch U43 Q 
      4348               50                2 Latch P43 Q 
      4611               54               87 Latch U42 Q 
      4697               54                1 Latch U16 Q 
      4783               55                2 Dummy
      5922               69               81 Latch JG Q 
      5930               69               73 Latch IG Q 
      5938               69               65 Latch HG Q 
      5947               69               56 Latch GG Q 
      5955               69               48 Latch FG Q 
      5963               69               40 Latch EG Q 
      5972               69               31 Latch DG Q 
      5980               69               23 Latch CG Q 
      5988               69               15 Latch BG Q 
      5996               69                7 Latch AG Q 
      6004               70               86 Latch U45 Q 
      6088               70                2 Latch U13 Q 
      6351               74               87 Latch U44 Q 
      6437               74                1 Latch U14 Q 
      6523               75                2 Dummy
      7488               87               81 Latch JF Q 
      7496               87               73 Latch IF Q 
      7504               87               65 Latch HF Q 
      7513               87               56 Latch GF Q 
      7521               87               48 Latch FF Q 
      7529               87               40 Latch EF Q 
      7538               87               31 Latch DF Q 
      7546               87               23 Latch CF Q 
      7554               87               15 Latch BF Q 
      7562               87                7 Latch AF Q 
      7570               88               86 Latch U47 Q 
      7654               88                2 Latch P44 Q 
      7917               92               87 Latch U46 Q 
      8003               92                1 Latch U12 Q 
      8089               93                2 Dummy
      9054              105               81 Latch JE Q 
      9062              105               73 Latch IE Q 
      9070              105               65 Latch HE Q 
      9079              105               56 Latch GE Q 
      9087              105               48 Latch FE Q 
      9095              105               40 Latch EE Q 
      9104              105               31 Latch DE Q 
      9112              105               23 Latch CE Q 
      9120              105               15 Latch BE Q 
      9128              105                7 Latch AE Q 
      9136              106               86 Latch U49 Q 
      9220              106                2 Latch U9 Q 
      9483              110               87 Latch P22 Q 
      9569              110                1 Latch U10 Q 
      9655              111                2 Dummy
     10794              125               81 Latch JD Q 
     10802              125               73 Latch ID Q 
     10810              125               65 Latch HD Q 
     10819              125               56 Latch GD Q 
     10827              125               48 Latch FD Q 
     10835              125               40 Latch ED Q 
     10844              125               31 Latch DD Q 
     10852              125               23 Latch CD Q 
     10860              125               15 Latch BD Q 
     10868              125                7 Latch AD Q 
     10876              126               86 Latch U51 Q 
     10960              126                2 Latch P2 Q 
     11223              130               87 Latch U50 Q 
     11309              130                1 Latch U8 Q 
     11395              131                2 Dummy
     12360              143               81 Latch JC Q 
     12368              143               73 Latch IC Q 
     12376              143               65 Latch HC Q 
     12385              143               56 Latch GC Q 
     12393              143               48 Latch FC Q 
     12401              143               40 Latch EC Q 
     12410              143               31 Latch DC Q 
     12418              143               23 Latch CC Q 
     12426              143               15 Latch BC Q 
     12434              143                7 Latch AC Q 
     12442              144               86 Latch U53 Q 
     12526              144                2 Latch P3 Q 
     12789              148               87 Latch P21 Q 
     12875              148                1 Latch U6 Q 
     12961              149                2 Dummy
     13926              161               81 Latch JB Q 
     13934              161               73 Latch IB Q 
     13942              161               65 Latch HB Q 
     13951              161               56 Latch GB Q 
     13959              161               48 Latch FB Q 
     13967              161               40 Latch EB Q 
     13976              161               31 Latch DB Q 
     13984              161               23 Latch CB Q 
     13992              161               15 Latch BB Q 
     14000              161                7 Latch AB Q 
     14008              162               86 Latch U55 Q 
     14092              162                2 Latch P5 Q 
     14355              166               87 Latch P20 Q 
     14441              166                1 Latch P4 Q 
     14527              167                2 Dummy
     15492              179               81 Latch JA Q 
     15500              179               73 Latch IA Q 
     15508              179               65 Latch HA Q 
     15517              179               56 Latch GA Q 
     15525              179               48 Latch FA Q 
     15533              179               40 Latch EA Q 
     15542              179               31 Latch DA Q 
     15550              179               23 Latch CA Q 
     15558              179               15 Latch BA Q 
     15566              179                7 Latch AA Q 
     15574              180               86 Latch P18 Q 
     15658              180                2 Latch P7 Q 
     15663              181               84 Dummy
     15754              182               80 Dummy
     15762              182               72 Dummy
     15770              182               64 Dummy
     15779              182               55 Dummy
     15787              182               47 Dummy
     15789              182               45 Dummy
     15795              182               39 Dummy
     15804              182               30 Dummy
     15812              182               22 Dummy
     15820              182               14 Dummy
     15828              182                6 Dummy
     15841              183               80 Dummy
     15876              183               45 Dummy
     15921              184               87 Latch P19 Q 
     15961              184               47 Dummy
     16002              184                6 Dummy
     16007              184                1 Latch P6 Q 
     16016              185               79 Dummy
     16093              185                2 Dummy
     16102              186               80 Dummy
     16176              186                6 Dummy
     16210              187               59 Dummy
     16235              187               34 Dummy
     16351              188                5 Dummy
     16657              192               47 Dummy
     16698              192                6 Dummy
     16744              193               47 Dummy
     16746              193               45 Dummy
     16748              193               43 Dummy
     16785              193                6 Dummy
     16789              193                2 Dummy
     16795              194               83 Dummy
     16796              194               82 Dummy
     16797              194               81 Dummy
     16800              194               78 Latch U58 Q 
     16808              194               70 Latch U60 Q 
     16816              194               62 Latch U62 Q 
     16825              194               53 Latch U64 Q 
     16831              194               47 Dummy
     16833              194               45 Dummy
     16835              194               43 Dummy
     16841              194               37 Latch U67 Q 
     16850              194               28 Latch U69 Q 
     16858              194               20 Latch U71 Q 
     16866              194               12 Latch U73 Q 
     16882              195               83 Dummy
     16883              195               82 Dummy
     16884              195               81 Dummy
     16918              195               47 Dummy
     16922              195               43 Dummy
     16969              196               83 Dummy
     16970              196               82 Dummy
     16971              196               81 Dummy
     16977              196               75 Latch P15 Q 
     16985              196               67 Latch P14 Q 
     16994              196               58 Latch P13 Q 
     17002              196               50 Latch U65 Q 
     17005              196               47 Dummy
     17009              196               43 Dummy
     17010              196               42 Latch U66 Q 
     17019              196               33 Latch U68 Q 
     17027              196               25 Latch P11 Q 
     17035              196               17 Latch P10 Q 
     17043              196                9 Latch P9 Q 
