Family XC3000A
Part InDesign
Cursor Arrow
Keycursor On
Mouse COM1 B1 Select B2 Menu B3 Done
Options ABL2XNF output_directory=xnf
Options APR -W -Y
Options HM2RPM dflt_logic=TRUE
Options LCA2XNF -G
Options MAKEBITS -S0 -R2 -XB -YA
Options MEMGEN output_directory=xnf
Options SDT2XNF -D xnf
Options WIR2XNF -B -OD xnf
Options XNF2WIR -B
Options XNFMERGE -A -D xnf
Options XSIMMAKE -F Viewlogic_Fpga_Func
